//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentBuilderLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class GoogleSheet : global::System.Configuration.ApplicationSettingsBase {
        
        private static GoogleSheet defaultInstance = ((GoogleSheet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GoogleSheet())));
        
        public static GoogleSheet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1A8447vaUYmBzsLT9QugIfcVYczwbtO3-1nsUCEuLC0M")]
        public string CONFIG_SHEET_ID {
            get {
                return ((string)(this["CONFIG_SHEET_ID"]));
            }
            set {
                this["CONFIG_SHEET_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Итоги")]
        public string RESULT_SHEET_NAME {
            get {
                return ((string)(this["RESULT_SHEET_NAME"]));
            }
            set {
                this["RESULT_SHEET_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Рейтинг")]
        public string SCORE_SHEET_NAME {
            get {
                return ((string)(this["SCORE_SHEET_NAME"]));
            }
            set {
                this["SCORE_SHEET_NAME"] = value;
            }
        }
    }
}
