//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentBuilderLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class GoogleSheet : global::System.Configuration.ApplicationSettingsBase {
        
        private static GoogleSheet defaultInstance = ((GoogleSheet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GoogleSheet())));
        
        public static GoogleSheet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1vY3Yibc_09a7h7Q8YkHj0axat510h0zkyI34UCn3c-c")]
        public string SHEET_ID {
            get {
                return ((string)(this["SHEET_ID"]));
            }
            set {
                this["SHEET_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Итоги")]
        public string RESULT_SHEET_NAME {
            get {
                return ((string)(this["RESULT_SHEET_NAME"]));
            }
            set {
                this["RESULT_SHEET_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Рейтинг")]
        public string SCORE_SHEET_NAME {
            get {
                return ((string)(this["SCORE_SHEET_NAME"]));
            }
            set {
                this["SCORE_SHEET_NAME"] = value;
            }
        }
    }
}
